require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/customer_tables", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CustomerTable. As you add validations to CustomerTable, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CustomerTable.create! valid_attributes
      get customer_tables_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      customer_table = CustomerTable.create! valid_attributes
      get customer_table_url(customer_table)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_customer_table_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      customer_table = CustomerTable.create! valid_attributes
      get edit_customer_table_url(customer_table)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CustomerTable" do
        expect {
          post customer_tables_url, params: { customer_table: valid_attributes }
        }.to change(CustomerTable, :count).by(1)
      end

      it "redirects to the created customer_table" do
        post customer_tables_url, params: { customer_table: valid_attributes }
        expect(response).to redirect_to(customer_table_url(CustomerTable.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CustomerTable" do
        expect {
          post customer_tables_url, params: { customer_table: invalid_attributes }
        }.to change(CustomerTable, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post customer_tables_url, params: { customer_table: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested customer_table" do
        customer_table = CustomerTable.create! valid_attributes
        patch customer_table_url(customer_table), params: { customer_table: new_attributes }
        customer_table.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the customer_table" do
        customer_table = CustomerTable.create! valid_attributes
        patch customer_table_url(customer_table), params: { customer_table: new_attributes }
        customer_table.reload
        expect(response).to redirect_to(customer_table_url(customer_table))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        customer_table = CustomerTable.create! valid_attributes
        patch customer_table_url(customer_table), params: { customer_table: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested customer_table" do
      customer_table = CustomerTable.create! valid_attributes
      expect {
        delete customer_table_url(customer_table)
      }.to change(CustomerTable, :count).by(-1)
    end

    it "redirects to the customer_tables list" do
      customer_table = CustomerTable.create! valid_attributes
      delete customer_table_url(customer_table)
      expect(response).to redirect_to(customer_tables_url)
    end
  end
end
